name: Hello Action
description: Prints hello

inputs:
  name:
    description: 'Who to greet'
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "Hello, ${{ inputs.name }}"